apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: solsa
      generate:
        command: [sh, -c]
        args: ["/solsa/solsa/node_modules/solsa/solsa yaml instance.js --config /solsa/solsa-config/solsa.yaml --cluster in-cluster --context in-cluster-context"]
