apiVersion: v1
kind: ConfigMap
metadata:
  name: solsa-cm
data:
  solsa.yaml: |
    clusters:
    - name: 'in-cluster'
      ingress:
        os: true
    contexts:
    - name: 'in-cluster-context'
      cluster: 'in-cluster'
